name: package and publish

on:
  push:
  pull_request:
    branches:
    - main
    
env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: 'src/Freedom.AspNetCore.Mvc.ViewEngine'
  PROJECT_NAME: 'Freedom.AspNetCore.Mvc.ViewEngine'
  BUILD_CONFIG: 'Release'

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Add package source
      run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.actor }}/index.json --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Install dependencies
      run: dotnet restore

    - name: Get version
      uses: bbonkr/get-version-action@v1
      id: get_version
      with:
        project: '${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME }}.csproj'
     
    - name: Build
      run: dotnet build --no-restore

    - name: Create NuGet package
      run: dotnet pack --configuration Release
    
    - name: Publish the package
      run: dotnet nuget push '${{ env.PROJECT_PATH }}/bin/${{ env.BUILD_CONFIG }}/*.nupkg' --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
    